version: '2'
services:
  elk-server:
    image: telminov/elk-server
    ports:
     - "0.0.0.0:5601:80"
     - "0.0.0.0:5044:5044"
    volumes:
     - /var/docker/elk_server/conf/nginx:/conf/nginx
     - /var/docker/elk_server/conf/logstash:/conf/logstash
     - /var/docker/elk_server/data:/data
     - /var/docker/elk_server/tls:/tls

#  elk-agent:
#    image: telminov/elk-agent
#    volumes:
#     - /var/docker/elk_agent/conf/:/conf/
#     - /var/docker/elk_agent/tls:/tls
#     - /var/log:/log/localhost
#    depends_on:
#      - elk-server