version: '2'
services:
  elk-server:
    image: telminov/elk-server
    ports:
     - "8051:80"
     - "5044:5044"
    volumes:
     - /var/docker/elk_server/data:/data
     - /var/docker/elk_server/conf/nginx:/conf/nginx
     - /var/docker/elk_server/tls:/tls
